feat: use new checkbox element
weweb-assets/ww-input-checkbox pull request #12
Opened 2022-04-05 11:26 UTC by AlexisJC

2022-04-05 11:38 UTC, AurelieV commented on src/wwElement.vue
> +            return !!this.variableValue || (this.wwEditorState.sidepanelContent.forceCheck && this.isEditing);
si c'est juste pour le style, c'est mieux de passer par le state no? ça permet de forcer plus de value

2022-04-05 11:38 UTC, AurelieV commented on ww-config.js
> +        checkbox: {
attention que ici, s'il y a des checbox sur plusieurs page (anciennes), et qu'ils republient sans aller sur la page, le contenu ne contiendra pas l'élément. Peut être ^révoir un fallback/migration?

2022-04-05 12:24 UTC, AlexisJC commented on src/wwElement.vue
> +            return !!this.variableValue || (this.wwEditorState.sidepanelContent.forceCheck && this.isEditing);
Quand tu dis state tu parles des states type hover, animation etc ? Parce que je voulais ça mais après quelques tests j'ai pensé que c'était pas possible 🤔

2022-04-06 15:29 UTC, Kramerbaf requested changes

2022-04-06 15:29 UTC, Kramerbaf commented on src/wwElement.vue
> +            return !!this.variableValue || (this.wwEditorState.sidepanelContent.forceCheck && this.isEditing);
Il vaut mieux retirer le forceChecked parce que sinon les gens vont l'utiliser et modifier le style et ça ne marchera pas. Parce que le state que tu passe à l'élément n'est pas récupéré par la sidebar qui va éditer le style "default" au lieu de "checked"

2022-04-06 15:29 UTC, Kramerbaf commented on ww-config.js
> +        checkbox: {
Tu peux mettre un bout de code qui fait que si "content.checkbox" n'existe pas ça utilise un input type="checkbox" comme avant ? comme ça on ne casse pas ce qui éxiste

2022-04-07 09:06 UTC, AurelieV commented on src/wwElement.vue
> +            :style="content.checkbox && 'display: none'"
tu peux passer des objets plutôt que des strings ;)

2022-04-07 13:58 UTC, merged